### ISSUE TITLE
[Suggestion] Option to block unlogged (annonymous) from changing one's wallpaper.

### ISSUE THREAD

**Issue by Deanskond** [PawCorp/walltaker#19]
I think it would get rather useful when project gets more popular.

**Comment by pupgray** [comment]
Valid! I've had this request before, but it's quite easy to make an account, especially since currently I don't verify emails (will come in the future) so even requireing an account won't block much IMO. Open to debate on that.

So the alternative that I currently have deployed is the "Friends only" mode for links, whereby you can approve individuals who are the only ones who can see/post to your Friends Only links.

**Comment by pupgray** [comment]
For now, I think I'll close this as I believe friends-only links solve this user story
